# The Docker image that will be used to build your app
image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - npm build
  - mkdir public
  - cp build public
  - cp src/server.js public

pages:
  script:
    - node public/server.js
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
