# Generated by Django 4.2.3 on 2023-09-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='templatelesson',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='templatelesson',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
