# Generated by Django 4.2.3 on 2023-09-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_lesson_id_homework_lesson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='lesson',
            new_name='lesson_ref',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='subject',
            new_name='subject_ref',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='teacher',
            new_name='teacher_ref',
        ),
        migrations.RenameField(
            model_name='templatelesson',
            old_name='subject',
            new_name='subject_ref',
        ),
        migrations.RenameField(
            model_name='templatelesson',
            old_name='teacher',
            new_name='teacher_ref',
        ),
    ]
